name: Process PDF with OCRmyPDF

on:
  workflow_dispatch:
    inputs:
      input_file:
        description: 'Input PDF file name from /input/ folder'
        required: true

jobs:
  process_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install OCRmyPDF
      run: |
        sudo apt-get update
        sudo apt-get install -y ocrmypdf

    - name: Process PDF
      run: |
        ocrmypdf -l tha ./input/${{ github.event.inputs.input_file }} ./output/output.pdf

    - name: Upload output PDF
      uses: actions/upload-artifact@v3
      with:
        name: output-pdf
        path: ./output/output.pdf
        retention-days: 7
