name: Process PDF with OCRmyPDF

on:
  workflow_dispatch:
    inputs:
      input_file:
        description: 'Input PDF file name from /input/ folder'
        required: true

permissions:
  contents: write

jobs:
  process_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install OCRmyPDF and Tesseract
      run: |
        echo "Current directory before apt-get update: $(pwd)"
        sudo apt-get update
        echo "apt-get update completed"
        sudo apt-get install -y ocrmypdf
        echo "OCRmyPDF installed at: $(which ocrmypdf)"
        sudo apt-get install -y tesseract-ocr-tha
        echo "Tesseract installed at: $(which tesseract)"

    - name: Process PDF
      run: |
        ocrmypdf -l tha+eng --clean --sidecar ./input/output_OCRmyPDF.txt ./input/${{ github.event.inputs.input_file }} ./input/output_OCRmyPDF.pdf
    # https://ocrmypdf.readthedocs.io/en/latest/cookbook.html

    - name: Upload output PDF
      uses: actions/upload-artifact@v4
      with:
        name: output-pdf
        path: |
          ./input/output_OCRmyPDF.pdf
          ./input/output_OCRmyPDF.txt
        retention-days: 7
