name: Process PDF with OCRmyPDF

on:
  workflow_dispatch:
    inputs:
      input_file:
        description: 'Input PDF file name from /input/ folder'
        required: true

permissions:
  contents: write

jobs:
  process_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache APT Packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Cache OCRmyPDF
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/ocrmypdf
        key: ${{ runner.os }}-ocrmypdf-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-ocrmypdf-

    - name: Cache Tesseract
      uses: actions/cache@v3
      with:
        path: /usr/share/tesseract-ocr
        key: ${{ runner.os }}-tesseract-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-tesseract-

    - name: Install OCRmyPDF and Tesseract
      run: |
        sudo apt-get update
        sudo apt-get install -y ocrmypdf
        sudo apt-get install -y tesseract-ocr-tha

    - name: Create output directory
      run: mkdir -p ./output

    - name: Process PDF
      run: |
        ocrmypdf -l tha ./input/${{ github.event.inputs.input_file }} ./output/output.pdf

    - name: Upload output PDF
      uses: actions/upload-artifact@v4
      with:
        name: output-pdf
        path: ./output/output.pdf
        retention-days: 7
