name: Batch File Processing with OCR

on:
  workflow_dispatch:
    inputs:
      file_type:
        description: 'Choose file type to process (PDF or Image)'
        required: true
        type: choice
        options:
          - pdf
          - image
      additional_param:
        description: 'Additional OCR parameters'
        required: false
        default: -l tha+eng

permissions:
  contents: write

jobs:
  process_files:
    runs-on: ubuntu-latest
    env:
      INPUT_DIR: ./input
      OUTPUT_DIR: ./output

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get file list
      id: get-files
      run: |
        case "${{ github.event.inputs.file_type }}" in
          pdf)
            find $INPUT_DIR -maxdepth 1 -iname '*.pdf' -printf '%f\n' > filelist.txt
            ;;
          image)
            find $INPUT_DIR -maxdepth 1 \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.tiff' -o -iname '*.bmp' \) -printf '%f\n' > filelist.txt
            ;;
        esac
        echo "files=$(base64 -w0 filelist.txt)" >> $GITHUB_OUTPUT

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ocrmypdf tesseract-ocr
        
        # Language installation logic
        lang_codes=$(echo "${{ github.event.inputs.additional_param }}" | sed -n 's/.*-l[[:space:]]*\([a-zA-Z]\{3\}\([+][a-zA-Z]\{3\}\)*\)\b.*/\1/p')
        if [ -n "$lang_codes" ]; then
          for lang_code in $(echo "$lang_codes" | tr '+' ' '); do
            if [ "$lang_code" = "eng" ]; then
              continue
            fi
            sudo apt-get install -y "tesseract-ocr-$lang_code"
          done
        fi

    - name: Process files
      env:
        FILE_LIST: ${{ steps.get-files.outputs.files }}
      run: |
        set -eo pipefail
        echo "$FILE_LIST" | base64 --decode > filelist.txt
        
        while IFS= read -r filename; do
          [ -z "$filename" ] && continue

          # Find exact filename with case matching
          original_file=$(find "$INPUT_DIR" -maxdepth 1 -iname "$filename" -print -quit)
          [ ! -f "$original_file" ] && { echo "File not found: $filename"; continue; }

          base_name=$(basename "$original_file")
          clean_base="${base_name%.*}"
          timestamp=$(date +"%Y%m%d_%H%M%S")

          case "${{ github.event.inputs.file_type }}" in
            pdf)
              ocrmypdf ${{ github.event.inputs.additional_param }} \
                --skip-text --clean \
                --output-type pdfa-2 \
                --quiet \
                --sidecar "$OUTPUT_DIR/${clean_base}_${timestamp}.txt" \
                "$original_file" "$OUTPUT_DIR/${clean_base}_${timestamp}.pdf"
              ;;
            image)
              tesseract ${{ github.event.inputs.additional_param }} \
                "$original_file" "$OUTPUT_DIR/${clean_base}_${timestamp}" pdf txt
              ;;
          esac

          # Force remove with exact filename case
          git rm -f --ignore-unmatch "$original_file"
          rm -f "$original_file"
          echo "Processed: $original_file → $OUTPUT_DIR/${clean_base}_${timestamp}.*"
        done < filelist.txt

    - name: Commit changes
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add -A
        git commit -m "Processed ${{ github.event.inputs.file_type }} files" || echo "No changes to commit"
        git push

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: processed-files
        path: $OUTPUT_DIR/*
        retention-days: 7
